### ISSUE TITLE
bug with start.sh and public keys

### ISSUE THREAD

**Issue by lionel87** [6arms1leg/git-ssh-docker#1]
I get a `cat: can't open '': No such file or directory` error when I start this container (no .pub ssh keys present in the /keys folder).
The start.sh script has a `cat ''` command that should be `echo ''` as far as I can tell.

https://github.com/6arms1leg/git-ssh-docker/blob/master/start.sh#L68

**Comment by 6arms1leg** [comment]
@lionel87, many thanks for taking the time to report this!

You are correct.  I updated the repository accordingly.
(Interestingly, although it gave an error message `cat ''` was still working as expected.)

BTW, you opened the very first issue. :tada:  I hope you find this project useful.

**Comment by lionel87** [comment]
@6arms1leg thanks for the fast reply! I found your project very useful!
